Add JSON Web Tokens (JWT) to the API Authentication Layer
Tresky/event-api pull request #4
Opened 2017-02-20 23:52 UTC by Tresky

Authentication Flow:
- Browser send request to login
- API verifies credentials
- If credentials are correct, a JWT is created containing the: ID of the user, the time the token is being issued, and the time that the token will expire.
- Token is hashed into a single string
- Hashed token is returned to the browser in the HTTP response

I also added the basis for revamping how controllers are handled. This is the `apiController.js` that you'll see in this pull request. This will allow us to add basic functionality to every controller (i.e. detecting current user, etc). This will be most helpful for the permissions layer.

2017-02-23 17:15 UTC, TylerGauntlett requested changes
Almost everything else was well commented and readable.

2017-02-23 17:15 UTC, TylerGauntlett commented on src/app.js
> +  if (req.method === 'OPTIONS') {
Add comment explaining this.

2017-02-23 20:53 UTC, Tresky commented on src/app.js
> +  if (req.method === 'OPTIONS') {
Done

2017-02-24 18:59 UTC, TylerGauntlett approved these changes

2017-02-24 19:49 UTC, merged